name: Deploy Next.js to VPS
on: [push]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: pull and deploy next.js
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/projects/demo-nextjs-on-vps
          git pull
          npm install
          npm run build
          pm2 delete all
          pm2 start ecosystem.config.js -i max